import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import HomeSection from '../components/HomeSection'
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Mahmoud | Full Stack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo.png" />
      </Head>
      <Navbar></Navbar>
      <HomeSection/>
      <About />
      <Skills />
      <Projects />
      <Contact />
        
    </div>
  )
}
